### ISSUE TITLE
Erro com alguns objetos

### ISSUE THREAD

**Issue by dougiteixeira** [oridestomkiel/home-assistant-correios#2]
Tenho enfrentado alguns erros com alguns objetos, por exemplo o objeto NX841419417BR.

Segue os logs de erro e o resultado da consulta referente a esse objeto.

```
2022-03-16 02:57:13 ERROR (MainThread) [homeassistant.components.sensor] correios: Error on device update!
Traceback (most recent call last):
  File "/workspaces/core/config/custom_components/correios/sensor.py", line 120, in async_update
    + eventos["unidade"]["endereco"]["cidade"]
KeyError: 'cidade'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspaces/core/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/workspaces/core/homeassistant/helpers/entity.py", line 717, in async_device_update
    await task
  File "/workspaces/core/config/custom_components/correios/sensor.py", line 140, in async_update
    _LOGGER.error("%s - Não foi possível atualizar - %s", self.info, error)
AttributeError: 'CorreiosSensor' object has no attribute 'info'
```

```
{"objetos":[{"codObjeto":"NX841419417BR","eventos":[{"codigo":"BDE","descricao":"Objeto não entregue - carteiro não atendido","detalhe":"Por favor, aguarde. Será realizada nova tentativa de entrega","dtHrCriado":"2022-03-15T11:08:20","tipo":"20","unidade":{"endereco":{"cidade":"FRANCA","uf":"SP"},"tipo":"Unidade de Distribuição"},"urlIcone":"/public-resources/img/logistica-reversa-cor.png"},{"codigo":"OEC","descricao":"Objeto saiu para entrega ao destinatário","dtHrCriado":"2022-03-15T09:06:36","tipo":"01","unidade":{"endereco":{"bairro":"VILA CHICO JULIO","cep":"14405972","cidade":"FRANCA","logradouro":"RUA ANTONIO BERNARDES PINTO","numero":"2946","uf":"SP"},"tipo":"Unidade de Distribuição"},"urlIcone":"/public-resources/img/pre-atendimento-cor.png"},{"codigo":"BDE","descricao":"Objeto não entregue - carteiro não atendido","detalhe":"Por favor, aguarde. Será realizada nova tentativa de entrega","dtHrCriado":"2022-03-14T10:55:16","tipo":"20","unidade":{"endereco":{"cidade":"FRANCA","uf":"SP"},"tipo":"Unidade de Distribuição"},"urlIcone":"/public-resources/img/logistica-reversa-cor.png"},{"codigo":"OEC","descricao":"Objeto saiu para entrega ao destinatário","dtHrCriado":"2022-03-14T09:05:16","tipo":"01","unidade":{"endereco":{"bairro":"VILA CHICO JULIO","cep":"14405972","cidade":"FRANCA","logradouro":"RUA ANTONIO BERNARDES PINTO","numero":"2946","uf":"SP"},"tipo":"Unidade de Distribuição"},"urlIcone":"/public-resources/img/pre-atendimento-cor.png"},{"codigo":"RO","descricao":"Objeto em trânsito - por favor aguarde","dtHrCriado":"2022-03-14T05:54:48","tipo":"01","unidade":{"endereco":{"cidade":"RIBEIRAO PRETO","uf":"SP"},"tipo":"Unidade de Tratamento"},"unidadeDestino":{"endereco":{"cidade":"FRANCA","uf":"SP"},"tipo":"Unidade de Distribuição"},"urlIcone":"/public-resources/img/caminhao-cor.png"},{"codigo":"RO","descricao":"Objeto em trânsito - por favor aguarde","dtHrCriado":"2022-03-13T12:24:30","tipo":"01","unidade":{"endereco":{"cidade":"RIBEIRAO PRETO","uf":"SP"},"tipo":"Unidade de Tratamento"},"unidadeDestino":{"endereco":{"cidade":"FRANCA","uf":"SP"},"tipo":"Unidade de Distribuição"},"urlIcone":"/public-resources/img/caminhao-cor.png"},{"codigo":"RO","descricao":"Objeto em trânsito - por favor aguarde","dtHrCriado":"2022-03-11T08:58:37","tipo":"01","unidade":{"endereco":{"cidade":"CURITIBA","uf":"PR"},"tipo":"Unidade de Logística Integrada"},"unidadeDestino":{"endereco":{"cidade":"RIBEIRAO PRETO","uf":"SP"},"tipo":"Unidade de Tratamento"},"urlIcone":"/public-resources/img/caminhao-cor.png"},{"codigo":"PAR","descricao":"Fiscalização aduaneira finalizada","dtHrCriado":"2022-03-11T08:30:11","tipo":"10","unidade":{"endereco":{"cidade":"CURITIBA","uf":"PR"},"tipo":"Unidade Operacional"},"urlIcone":"/public-resources/img/verificar-documento-cor.png"},{"codigo":"PAR","descricao":"Objeto recebido pelos Correios do Brasil","dtHrCriado":"2022-03-08T20:01:03","tipo":"16","unidade":{"endereco":{"cidade":"CURITIBA","uf":"PR"},"tipo":"Unidade de Logística Integrada"},"urlIcone":"/public-resources/img/brazil.png"},{"codigo":"PO","descricao":"Objeto postado","dtHrCriado":"2022-03-06T23:00:16","tipo":"01","unidade":{"codSro":"00156000","endereco":{},"nome":"CHINA","tipo":"País"},"destinatario":{},"urlIcone":"/public-resources/img/agencia-cor.png"}],"modalidade":"F","tipoPostal":{"categoria":"PACKET STANDARD IMPORTAÇÃO","descricao":"CORREIOS PACKET STANDARD","sigla":"NX"},"habilitaAutoDeclaracao":false,"permiteEncargoImportacao":false,"habilitaPercorridaCarteiro":false,"bloqueioObjeto":false,"possuiLocker":false,"habilitaLocker":false,"habilitaCrowdshipping":false}],"quantidade":1,"resultado":"Todos os Eventos","versao":"1.7.3"}
```

**Comment by oridestomkiel** [comment]
Adicionado condição para ignorar eventos sem cidade
